#!/bin/sh
export PATH=/usr/local/bin:/usr/bin:/bin
cd /var/www/nobleape
#Uncomment the following line to enable the Noble Ape web server
#naweb --land 6342 --sim realtime.txt --output realtime.txt -a apescript.txt

